export const manoharDairyMenu = [
      {
        itemName: "Chole Bhature",
      description: "Spicy chickpea curry served with two fluffy bhaturas.",
      price: 150,
      category: "Main Course",
      type: "Vegetarian",
      image: {
        url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 521, protein: 23 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Raj Kachori",
        description: "Crispy kachori filled with potatoes, sprouts, and sweet curd.",
        price: 120,
        category: "Snacks",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 272, protein: 32 },
        status: "available",
      },
      {
        itemName: "Paneer Tikka",
        description: "Marinated cottage cheese cubes grilled to perfection.",
        price: 250,
        category: "Starters",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 469, protein: 14 },
        status: "available",
        isRecommended: true,
      },
      {
        itemName: "Masala Dosa",
      description: "Crispy rice crepe filled with spiced potato mash, served with sambar and chutney.",
      price: 130,
      category: "Main Course",
      type: "Vegetarian",
      image: {
        url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 582, protein: 18 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Rasmalai (2 Pcs)",
        description: "Soft cottage cheese dumplings soaked in sweetened, thickened milk.",
        price: 90,
        category: "Dessert",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 519, protein: 27 },
        status: "available",
      },
      {
        itemName: "Deluxe Veg Thali",
        description: "A complete meal with dal makhani, shahi paneer, mix veg, rice, raita, sweet, and breads.",
        price: 299,
        category: "Thali",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 248, protein: 22 },
        status: "available",
        isRecommended: true,
      }
    ];
