export const sagarGaireMenu = [
      {
        itemName: "Veg Cheese Burger",
        description: "Signature crispy patty with double cheese and creamy mayo.",
        price: 90,
        category: "Burger",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 323, protein: 30 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "White Sauce Pasta",
        description: "Penne pasta tossed in rich, creamy, cheesy white sauce.",
        price: 150,
        category: "Italian",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 281, protein: 18 },
        status: "available",
      },
      {
        itemName: "Cold Coffee",
        description: "Thick, creamy, and refreshing cold coffee.",
        price: 80,
        category: "Beverages",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 307, protein: 13 },
        status: "available",
        isRecommended: true,
      },
      {
        itemName: "Cheese Corn Sandwich",
        description: "Grilled sandwich stuffed with sweet corn and melted cheese.",
        price: 110,
        category: "Snacks",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 534, protein: 18 },
        status: "available",
      },
      {
        itemName: "Veg Wrap",
        description: "Tortilla wrapped with crispy veggies, sauces, and cheese.",
        price: 100,
        category: "Wrap",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 205, protein: 27 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Red Sauce Pasta",
        description: "Tangy tomato-based pasta loaded with vegetables.",
        price: 140,
        category: "Italian",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 202, protein: 33 },
        status: "available",
      }
    ];
