export const sharmaVishnuMenu = [
      {
        itemName: "Veg Manchurian",
        description: "Crispy vegetable balls tossed in spicy soy gravy.",
        price: 160,
        category: "Chinese",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 324, protein: 16 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Hakka Noodles",
        description: "Wok-tossed noodles with fresh vegetables and sauces.",
        price: 140,
        category: "Chinese",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 597, protein: 31 },
        status: "available",
      },
      {
        itemName: "Paneer Chilli",
        description: "Spicy and tangy paneer cubes cooked Chinese style.",
        price: 190,
        category: "Starters",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 298, protein: 20 },
        status: "available",
      },
      {
        itemName: "Veg Fried Rice",
        description: "Aromatic basmati rice tossed with fresh chopped vegetables.",
        price: 130,
        category: "Chinese",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 346, protein: 10 },
        status: "available",
      },
      {
        itemName: "Spring Rolls",
        description: "Crispy fried rolls stuffed with a savory mixed vegetable filling.",
        price: 120,
        category: "Snacks",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 539, protein: 33 },
        status: "available",
        isRecommended: true,
      },
      {
        itemName: "Honey Chilli Potato",
        description: "Crispy potato fries glazed in a sweet and spicy honey sauce.",
        price: 150,
        category: "Starters",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 314, protein: 7 },
        status: "available",
      }
    ];
