export const zamZamMenu = [
      {
        itemName: "Chicken Biryani",
        description: "Aromatic basmati rice layered with spiced chicken.",
        price: 220,
        category: "Biryani",
        type: "Non-Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 556, protein: 23 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Mutton Korma",
        description: "Tender mutton pieces cooked in rich Mughlai gravy.",
        price: 350,
        category: "Main Course",
        type: "Non-Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 244, protein: 20 },
        status: "available",
      },
      {
        itemName: "Chicken Shawarma",
        description: "Juicy grilled chicken wrapped in soft pita bread.",
        price: 110,
        category: "Wrap",
        type: "Non-Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 279, protein: 24 },
        status: "available",
        isRecommended: true,
      },
      {
        itemName: "Tandoori Chicken (Half)",
      description: "Chicken marinated in yogurt and spices, roasted in a tandoor.",
      price: 280,
      category: "Main Course",
      type: "Non-Vegetarian",
      image: {
        url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 318, protein: 21 },
        status: "available",
        isTopRated: true,
      },
      {
        itemName: "Butter Chicken",
        description: "Classic creamy tomato curry with tender chicken pieces.",
        price: 320,
        category: "Main Course",
        type: "Non-Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 260, protein: 6 },
        status: "available",
      },
      {
        itemName: "Rumali Roti",
        description: "Extremely thin, soft bread served folded like a handkerchief.",
        price: 20,
        category: "Breads",
        type: "Vegetarian",
        image: { url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=400" },
        macros: { calories: 324, protein: 5 },
        status: "available",
      }
    ];
